import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/session.dart';

class PdfExportService {
  static const _red = PdfColor.fromInt(0xFFD40000);
  static const _redLight = PdfColor.fromInt(0xFFFFF0F0);
  static const _amber = PdfColor.fromInt(0xFFE65100);
  static const _grey600 = PdfColor.fromInt(0xFF757575);
  static const _grey200 = PdfColor.fromInt(0xFFEEEEEE);

  Future<void> shareSchedule({
    required List<Session> sessions,
    required Set<String> lockedIds,
    required Set<String> conflictIds,
  }) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: await PdfGoogleFonts.notoSansRegular(),
        bold: await PdfGoogleFonts.notoSansBold(),
      ),
    );

    final grouped = _groupByDate(sessions);
    final sortedDates = grouped.keys.toList()..sort();
    final dateFormatter = DateFormat('EEEE, MMMM d, yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 48),
        header: (_) => _buildHeader(sessions.length, sortedDates.length),
        footer: (ctx) => _buildFooter(ctx),
        build: (ctx) => [
          for (final dateKey in sortedDates) ...[
            _dateHeader(dateFormatter.format(grouped[dateKey]!.first.startTime)),
            pw.SizedBox(height: 6),
            for (final session in grouped[dateKey]!)
              _sessionBlock(
                session,
                isLocked: lockedIds.contains(session.id),
                hasConflict: conflictIds.contains(session.id),
              ),
            pw.SizedBox(height: 8),
          ],
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'redcapcon_2026_schedule.pdf',
    );
  }

  Map<String, List<Session>> _groupByDate(List<Session> sessions) {
    final Map<String, List<Session>> grouped = {};
    for (final s in sessions) {
      grouped.putIfAbsent(s.dateKey, () => []).add(s);
    }
    return grouped;
  }

  pw.Widget _buildHeader(int sessionCount, int dayCount) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'REDCapCon 2026',
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: _red,
                  ),
                ),
                pw.Text(
                  'My Personal Schedule',
                  style: pw.TextStyle(fontSize: 13, color: _grey600),
                ),
              ],
            ),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
              decoration: pw.BoxDecoration(
                color: _redLight,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Text(
                '$sessionCount session${sessionCount == 1 ? '' : 's'}  •  $dayCount day${dayCount == 1 ? '' : 's'}',
                style: pw.TextStyle(fontSize: 11, color: _red, fontWeight: pw.FontWeight.bold),
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Divider(color: _red, thickness: 1.5),
        pw.SizedBox(height: 8),
      ],
    );
  }

  pw.Widget _buildFooter(pw.Context ctx) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by REDCapCon App',
          style: pw.TextStyle(fontSize: 9, color: _grey600),
        ),
        pw.Text(
          'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
          style: pw.TextStyle(fontSize: 9, color: _grey600),
        ),
      ],
    );
  }

  pw.Widget _dateHeader(String label) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: pw.BoxDecoration(
        color: const PdfColor.fromInt(0xFF4A6FA5),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(
        label,
        style: pw.TextStyle(
          fontSize: 13,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
        ),
      ),
    );
  }

  pw.Widget _sessionBlock(Session session, {required bool isLocked, required bool hasConflict}) {
    final timeText =
        '${_pad(session.startTime.hour)}:${_pad(session.startTime.minute)}  –  '
        '${_pad(session.endTime.hour)}:${_pad(session.endTime.minute)}';

    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 6),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: hasConflict
            ? const PdfColor.fromInt(0xFFFFF8E1)
            : const PdfColor.fromInt(0xFFFAFAFA),
        border: pw.Border(
          left: pw.BorderSide(
            color: isLocked ? _red : (hasConflict ? _amber : _grey200),
            width: isLocked ? 3 : (hasConflict ? 3 : 1),
          ),
          top: pw.BorderSide(color: _grey200),
          bottom: pw.BorderSide(color: _grey200),
          right: pw.BorderSide(color: _grey200),
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Text(
                  session.title,
                  style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
                ),
              ),
              if (isLocked)
                pw.Container(
                  margin: const pw.EdgeInsets.only(left: 6),
                  padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                  decoration: pw.BoxDecoration(
                    color: _redLight,
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                  child: pw.Text(
                    'My Session',
                    style: pw.TextStyle(fontSize: 9, color: _red, fontWeight: pw.FontWeight.bold),
                  ),
                ),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Row(
            children: [
              pw.Text(timeText, style: pw.TextStyle(fontSize: 10, color: _grey600)),
              pw.SizedBox(width: 12),
              pw.Text(session.location, style: pw.TextStyle(fontSize: 10, color: _grey600)),
              if (hasConflict) ...[
                pw.SizedBox(width: 10),
                pw.Text(
                  '[!] Time conflict',
                  style: pw.TextStyle(fontSize: 9, color: _amber, fontWeight: pw.FontWeight.bold),
                ),
              ],
            ],
          ),
          if (session.speaker.isNotEmpty) ...[
            pw.SizedBox(height: 3),
            pw.Text(session.speaker, style: pw.TextStyle(fontSize: 10, color: _grey600)),
          ],
          pw.SizedBox(height: 5),
          pw.Row(
            children: [
              _tag(session.type, background: const PdfColor.fromInt(0xFFE3F2FD), text: const PdfColor.fromInt(0xFF1565C0)),
              pw.SizedBox(width: 6),
              _tag(session.audience, background: const PdfColor.fromInt(0xFFE8F5E9), text: const PdfColor.fromInt(0xFF2E7D32)),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _tag(String label, {required PdfColor background, required PdfColor text}) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 7, vertical: 3),
      decoration: pw.BoxDecoration(
        color: background,
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Text(label, style: pw.TextStyle(fontSize: 9, color: text, fontWeight: pw.FontWeight.bold)),
    );
  }

  String _pad(int n) => n.toString().padLeft(2, '0');
}
